FROM adoptopenjdk/openjdk11:alpine
LABEL Maintainer = Bartlomiej Paluch
ENV LOGGER_PORT = 8888
ENV LOGGER_USERNAME = postgres
ENV LOGGER_PASSWORD = qwe123
ENV POSTGRES_IP = postgres
ENV POSTGRES_PORT = 5432
ENV LOG_DB = logdb
ENV BROKER_IP = kafka
ENV BROKER_PORT = 9092
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} logs.jar
CMD ["java","-jar","/logs.jar"]