apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-config
  labels:
    app: ai
data:
  UPLOADER: http://uploader:8999
  KAFKA_HOST: kafka:9092
  BLOG: http://blog:8001/api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  selector:
    matchLabels:
      app: ai
  replicas: 2
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: bfinger1997/ai
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ai-config