FROM python:3
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
LABEL Maintainer = Bartlomiej Paluch
ENV UPLOADER = http://uploader:8999
ENV BLOG = http://blog:8001/api


RUN pip install -r requirements.txt
CMD ["python", "main.py"]